### ISSUE TITLE
Add an option for clean URLs

### ISSUE THREAD

**Issue by benoitchantre** [RayViljoen/grunt-sitemap#24]
Actually, the plugin use the file extension in the URLs.
It would be nice to have an option to remove the extension if you prefer to use clean URLs.

**Comment by counterbeing** [comment]
This looks good to me! Thanks for contributing. I'm slow to get around to these things, so sorry!

**Comment by counterbeing** [comment]
I'm going to close this issue because I've just merged in your changes to the master, and cut a new release.

**Comment by benoitchantre** [comment]
Thanks everybody for this improvement.
