### ISSUE TITLE
Time to say bye to CoffeeScript

### ISSUE THREAD

**Issue by RayViljoen** [RayViljoen/grunt-sitemap#39]
Need to convert coffee files to JS.

Decaffeinate output seems ok, but will require a small bit of tweaking.

https://github.com/decaffeinate/decaffeinate#readme

**Comment by XhmikosR** [comment]
@RayViljoen: can you add me as a collaborator and on npm if you want?

I already made the changes locally.

**Comment by XhmikosR** [comment]
OK I pushed my patches to my fork for now https://github.com/RayViljoen/grunt-sitemap/compare/master...XhmikosR:dev?w=1

Tested with one project, all good.
